### ISSUE TITLE
fixed images on safari mobile not scaling

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#366]
As @larrysalibra pointed out in Slack #design, fixed images on safari mobile are not scaling or adjusting with the viewport size.

<img width="590" alt="screenshot 2017-08-11 15 04 25" src="https://user-images.githubusercontent.com/1711854/29228083-65faca44-7ea6-11e7-9c62-4239ecf2f35f.png">

**Comment by guylepage3** [comment]
resolved issue by removing the image sections for the time being on mobile devices.

**Comment by larrysalibra** [comment]
I'm still seeing this problem on my 10.5 iPad in both landscape and portrait orientations:

![img_0072](https://user-images.githubusercontent.com/597182/29313303-e578cb16-81eb-11e7-964f-ef1ae31efe96.PNG)
![img_0073](https://user-images.githubusercontent.com/597182/29313321-f7a068a8-81eb-11e7-8581-94fcfb0e3db1.PNG)

**Comment by guylepage3** [comment]
Ha. I know why.. I've hidden the two div's for tablet and below as i could not find a fix to mobile safari's bug. a better solution would be to detect if it's mobile safari and then hide the divs that way.
